# Fashion E-commerce Analytics — Data Understanding

## Objective

The objective of this notebook is to understand and profile the raw datasets before any transformation or cleaning.

In [45]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.max_colwidth", 100)

In [ ]:
from pathlib import Path

DATA_PATH = Path("../data/raw")

customers = pd.read_csv(DATA_PATH / "customers.csv")
discounts = pd.read_csv(DATA_PATH / "discounts.csv")
employees = pd.read_csv(DATA_PATH / "employees.csv")
products = pd.read_csv(DATA_PATH / "products.csv")
stores = pd.read_csv(DATA_PATH / "stores.csv")
transactions = pd.read_csv(DATA_PATH / "transactions.csv")

C:\Users\dell\AppData\Local\Temp\ipykernel_27784\2487924647.py:5: DtypeWarning: Columns (0: Telephone) have mixed types. Specify dtype option on import or set low_memory=False.
  customers = pd.read_csv(DATA_PATH / "customers.csv")

In [47]:
print("Customers:", customers.shape)
print("Discounts:", discounts.shape)
print("Employees:", employees.shape)
print("Products:", products.shape)
print("Stores:", stores.shape)
print("Transactions:", transactions.shape)

Customers: (1643306, 9)
Discounts: (181, 6)
Employees: (404, 4)
Products: (17940, 12)
Stores: (35, 8)
Transactions: (6416827, 19)

In [48]:
customers.head()

,Customer ID,Name,Email,Telephone,City,Country,Gender,Date Of Birth,Job Title
0,1,Tyler Garcia,tyler.garcia@fake_gmail.com,922.970.2265x47563,New York,United States,M,2003-07-15,NaN
1,2,Joshua Miller,joshua.miller@fake_gmail.com,+1-958-729-6169,New York,United States,M,2000-06-16,Records manager
2,3,Alison Marshall DDS,alison.marshall.dds@fake_hotmail.com,+1-645-567-0876x5409,New York,United States,F,2003-07-22,NaN
3,4,Jeffery Acosta,jeffery.acosta@fake_yahoo.com,212.336.0912x84994,New York,United States,M,1996-11-12,Proofreader
4,5,Ashley Sanders,ashley.sanders@fake_hotmail.com,7814535781,New York,United States,F,1998-02-10,Exercise physiologist

In [49]:
products.head()

,Product ID,Category,Sub Category,Description PT,Description DE,Description FR,Description ES,Description EN,Description ZH,Color,Sizes,Production Cost
0,1,Feminine,Coats and Blazers,Esportivo Veludo Verde Com Botões,Sport Samt Sport Mit Knöpfen,Sports Velvet Sports Avec Des Boutons,Deportes De Terciopelo Con Botones,Sports Velvet Sports With Buttons,运动天鹅绒运动与按钮,NaN,S|M|L|XL,10.73
1,2,Feminine,Sweaters and Knitwear,Luxuoso Denim Rosa Com Botões,Luxuriöser Rosa Jeans Mit Knöpfen,Léchard De Denim Rose Avec Boutons,Denim Rosa Lujoso Con Botones,Luxurious Pink Denim With Buttons,豪华的粉红色牛仔布和纽扣,PINK,S|M|L|XL,19.55
2,3,Feminine,Dresses and Jumpsuits,Retrô Tricot Preto Estampado,Black Tricot Gedruckter Tricot,Tricot Imprimé En Tricot Noir,Tricot Negro Tricot Impreso,Black Tricot Printed Tricot,黑色三角形印刷三角形,BLACK,S|M|L|XL,25.59
3,4,Feminine,Shirts and Blouses,Blusa De Algodão Básica,Basis -Baumwollbluse,Chemisier En Coton De Base,Blusa De Algodón,Basic Cotton Blouse,基本的棉衬衫,NaN,S|M|L|XL,27.62
4,5,Feminine,T-shirts and Tops,T-Shirt Básica De Algodão,Basis-Baumwoll-T-Shirt,T-Shirt En Coton De Base,Camiseta Básica De Algodón,Basic Cotton T-Shirt,基本棉T恤,NaN,S|M|L,11.69

In [50]:
stores.head()

,Store ID,Country,City,Store Name,Number of Employees,ZIP Code,Latitude,Longitude
0,1,United States,New York,Store New York,10,10001,40.7128,-74.0060
1,2,United States,Los Angeles,Store Los Angeles,8,90001,34.0522,-118.2437
2,3,United States,Chicago,Store Chicago,9,60601,41.8781,-87.6298
3,4,United States,Houston,Store Houston,10,77001,29.7604,-95.3698
4,5,United States,Phoenix,Store Phoenix,9,85001,33.4484,-112.0740

In [51]:
transactions.head()

,Invoice ID,Line,Customer ID,Product ID,Size,Color,Unit Price,Quantity,Date,Discount,Line Total,Store ID,Employee ID,Currency,Currency Symbol,SKU,Transaction Type,Payment Method,Invoice Total
0,INV-US-001-03558761,1,47162,485,M,NaN,80.5,1,2023-01-01 15:42:00,0.0,80.5,1,7,USD,$,MASU485-M-,Sale,Cash,126.7
1,INV-US-001-03558761,2,47162,2779,G,NaN,31.5,1,2023-01-01 15:42:00,0.4,18.9,1,7,USD,$,CHCO2779-G-,Sale,Cash,126.7
2,INV-US-001-03558761,3,47162,64,M,NEUTRAL,45.5,1,2023-01-01 15:42:00,0.4,27.3,1,7,USD,$,MACO64-M-NEUTRAL,Sale,Cash,126.7
3,INV-US-001-03558762,1,10142,131,M,BLUE,70.0,1,2023-01-01 20:04:00,0.4,42.0,1,6,USD,$,FECO131-M-BLUE,Sale,Cash,77.0
4,INV-US-001-03558762,2,10142,716,L,WHITE,26.0,1,2023-01-01 20:04:00,0.0,26.0,1,6,USD,$,MAT-716-L-WHITE,Sale,Cash,77.0

In [52]:
def dataset_info(df, name):
    print(f"\n{'=' * 60}")
    print(f"{name}")
    print(f"{'=' * 60}")
    print(f"Rows: {df.shape[0]}")
    print(f"Columns: {df.shape[1]}")
    print("\nData types:")
    print(df.dtypes)

In [53]:
dataset_info(customers, "CUSTOMERS")

============================================================
CUSTOMERS
============================================================
Rows: 1643306
Columns: 9

Data types:
Customer ID       int64
Name                str
Email               str
Telephone        object
City                str
Country             str
Gender              str
Date Of Birth       str
Job Title           str
dtype: object

In [54]:
dataset_info(discounts, "DISCOUNTS")

============================================================
DISCOUNTS
============================================================
Rows: 181
Columns: 6

Data types:
Start               str
End                 str
Discont         float64
Description         str
Category            str
Sub Category        str
dtype: object

In [55]:
dataset_info(employees, "EMPLOYEES")

============================================================
EMPLOYEES
============================================================
Rows: 404
Columns: 4

Data types:
Employee ID    int64
Store ID       int64
Name             str
Position         str
dtype: object

In [56]:
dataset_info(products, "PRODUCTS")

============================================================
PRODUCTS
============================================================
Rows: 17940
Columns: 12

Data types:
Product ID           int64
Category               str
Sub Category           str
Description PT         str
Description DE         str
Description FR         str
Description ES         str
Description EN         str
Description ZH         str
Color                  str
Sizes                  str
Production Cost    float64
dtype: object

In [57]:
dataset_info(stores, "STORES")

============================================================
STORES
============================================================
Rows: 35
Columns: 8

Data types:
Store ID                 int64
Country                    str
City                       str
Store Name                 str
Number of Employees      int64
ZIP Code                   str
Latitude               float64
Longitude              float64
dtype: object

In [58]:
dataset_info(transactions, "TRANSACTIONS")

============================================================
TRANSACTIONS
============================================================
Rows: 6416827
Columns: 19

Data types:
Invoice ID              str
Line                  int64
Customer ID           int64
Product ID            int64
Size                    str
Color                   str
Unit Price          float64
Quantity              int64
Date                    str
Discount            float64
Line Total          float64
Store ID              int64
Employee ID           int64
Currency                str
Currency Symbol         str
SKU                     str
Transaction Type        str
Payment Method          str
Invoice Total       float64
dtype: object

In [59]:
def missing_values(df, name):
    result = pd.DataFrame({
        "Missing": df.isna().sum(),
        "Missing %": (df.isna().mean() * 100).round(2)
    })
    
    result = result[result["Missing"] > 0]
    
    print(f"\n{name}")
    display(result.sort_values("Missing", ascending=False))

In [60]:
missing_values(customers, "CUSTOMERS")

CUSTOMERS

           Missing  Missing %
Job Title   584185      35.55

In [61]:
missing_values(discounts, "DISCOUNTS")

DISCOUNTS

              Missing  Missing %
Category           10       5.52
Sub Category       10       5.52

In [62]:
missing_values(employees, "EMPLOYEES")

EMPLOYEES

Empty DataFrame
Columns: [Missing, Missing %]
Index: []

In [63]:
missing_values(products, "PRODUCTS")

PRODUCTS

       Missing  Missing %
Color    12445      69.37
Sizes     2070      11.54

In [64]:
missing_values(stores, "STORES")

STORES

Empty DataFrame
Columns: [Missing, Missing %]
Index: []

In [65]:
missing_values(transactions, "TRANSACTIONS")

TRANSACTIONS

       Missing  Missing %
Color  4350783      67.80
Size    413102       6.44

In [66]:
def duplicate_info(df, name):
    duplicates = df.duplicated().sum()
    print(f"{name}: {duplicates} duplicated rows")

duplicate_info(customers, "CUSTOMERS")
duplicate_info(discounts, "DISCOUNTS")
duplicate_info(employees, "EMPLOYEES")
duplicate_info(products, "PRODUCTS")
duplicate_info(stores, "STORES")
duplicate_info(transactions, "TRANSACTIONS")

CUSTOMERS: 0 duplicated rows
DISCOUNTS: 0 duplicated rows
EMPLOYEES: 0 duplicated rows
PRODUCTS: 0 duplicated rows
STORES: 0 duplicated rows
TRANSACTIONS: 798 duplicated rows

In [67]:
key_checks = {
    "Customer ID": customers["Customer ID"],
    "Product ID": products["Product ID"],
    "Store ID": stores["Store ID"],
    "Employee ID": employees["Employee ID"],
    "Invoice ID": transactions["Invoice ID"]
}

for key, series in key_checks.items():
    print(
        f"{key}: "
        f"{series.nunique()} unique values / "
        f"{len(series)} rows"
    )

Customer ID: 1643306 unique values / 1643306 rows
Product ID: 17940 unique values / 17940 rows
Store ID: 35 unique values / 35 rows
Employee ID: 404 unique values / 404 rows
Invoice ID: 4540404 unique values / 6416827 rows

In [68]:
customer_ids = set(customers["Customer ID"])

missing_customers = transactions[
    ~transactions["Customer ID"].isin(customer_ids)
]

print("Transactions with unknown Customer ID:",
      len(missing_customers))

Transactions with unknown Customer ID: 0

In [69]:
product_ids = set(products["Product ID"])

missing_products = transactions[
    ~transactions["Product ID"].isin(product_ids)
]

print("Transactions with unknown Product ID:",
      len(missing_products))

Transactions with unknown Product ID: 0

In [70]:
store_ids = set(stores["Store ID"])

missing_stores = transactions[
    ~transactions["Store ID"].isin(store_ids)
]

print("Transactions with unknown Store ID:",
      len(missing_stores))

Transactions with unknown Store ID: 0

In [71]:
employee_ids = set(employees["Employee ID"])

missing_employees = transactions[
    ~transactions["Employee ID"].isin(employee_ids)
]

print("Transactions with unknown Employee ID:",
      len(missing_employees))

Transactions with unknown Employee ID: 0